export const metadata = {
  title: "Next Routing POC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="om">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
